### ISSUE TITLE
[Compatibility Report] Testing mods with leafculling 0.1.0

### ISSUE THREAD

**Issue by quentin452** [basdxz/LeafCulling#1]
BIome o' Plenty : game not starting
Other incompatible mods : leaves not culled

edit :If you use bugtorch + witchery disable fixWitcheryLeavesShearDupeAndOptifineRendering in bugtorch cfg to provide a compat for leafculling

Html version : 

<table>
    <thead>
        <tr>
            <td style="text-align:center">
            <th colspan="3">Leaf Culling Testing Compatibility 0.1.0</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td>Compatible</td>
            <td>Incompatible</td>
        </tr>
            <td>ExtrabiomesXL</td>
            <td style="text-align:center">X</td>
            <td></td>
              </tr>
            <td>Chisel</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Twilight forest</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Atum</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Withcery</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Forestry</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Tinker's Construct</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Minefactory Reloaded</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Aether</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Aether II</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Biome O' Plenty</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Tropicraft</td>
            <td style="text-align:center">X</td>
            <td></td>
    </tbody>
</table>

```
<table>
    <thead>
        <tr>
            <td style="text-align:center">
            <th colspan="3">Leaf Culling Testing Compatibility 0.1.0</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td>Compatible</td>
            <td>Incompatible</td>
        </tr>
            <td>ExtrabiomesXL</td>
            <td style="text-align:center">X</td>
            <td></td>
              </tr>
            <td>Chisel</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Twilight forest</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Atum</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Withcery</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Forestry</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Tinker's Construct</td>
            <td style="text-align:center">X</td>
            <td></td>
        </tr>
            <td>Minefactory Reloaded</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Aether</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Aether II</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Biome O' Plenty</td>
            <td></td>
            <td style="text-align:center">X</td>
        </tr>
            <td>Tropicraft</td>
            <td style="text-align:center">X</td>
            <td></td>
    </tbody>
</table>
```

**Comment by basdxz** [comment]
Compatibility for all mods now implemented and tested outside of dev
