### ISSUE TITLE
[2 questions] Is it possible to cull leaves if there is space in between, and cull leaves if two different leaves are side by side

### ISSUE THREAD

**Issue by quentin452** [basdxz/LeafCulling#4]
space between

![Capture d’écran_2022-10-04_00-02-58](https://user-images.githubusercontent.com/42176772/193694075-aaa3d7b5-dc77-49be-8db6-15f39a23c142.png)

side by side

![Capture d’écran_2022-10-04_00-29-19](https://user-images.githubusercontent.com/42176772/193697272-822f9950-9a73-42f5-9a16-bfc54cafc22f.png)

**Comment by Houstonruss** [comment]
Like this?
![193694075-aaa3d7b5-dc77-49be-8db6-15f39a23c142](https://user-images.githubusercontent.com/50430417/194110074-46b33986-fc04-42ca-b022-10c2423fb68e.png)

**Comment by quentin452** [comment]
> Like this? ![193694075-aaa3d7b5-dc77-49be-8db6-15f39a23c142](https://user-images.githubusercontent.com/50430417/194110074-46b33986-fc04-42ca-b022-10c2423fb68e.png)

????

**Comment by basdxz** [comment]
Both of these are desired behaviour as-is. 

The first would mess up many kinds of builds, and in general look awkward without providing any tangible benefit.

The second is also desired behaviour, the different types of leaves act in an equivalent manner to stained glass.
